const products = [
    {
        id: 1,
        name_en: 'Coconut',
        name_vi: 'Nước Dừa',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 4,
        discount: 30,
        categories: [3],
    },
    {
        id: 2,
        name_en: 'Aquafina en',
        name_vi: 'Aquafina vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail: 'https://sonhawater.com/wp-content/uploads/2020/01/nuoc-aquafina.jpg',
        amount: 7,
        discount: 30,
        categories: [1],
    },
    {
        id: 3,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://cafebiz.cafebizcdn.vn/zoom/700_438/2016/coca-cola-commercial-photography-1463360698380-crop-1463360708561.jpg',
        amount: 10,
        discount: 30,
        categories: [2],
    },
    {
        id: 4,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 10,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 5,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 10,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 6,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 10,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 7,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 10,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 8,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 10,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 9,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 1,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 10,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 1,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 11,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 1,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 12,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 1,
        discount: 30,
        categories: [2, 3],
    },
    {
        id: 13,
        name_en: 'Coca-cola en',
        name_vi: 'Coca-cola vi',
        price: 10000,
        sellPrice: 9000,
        thumbnail:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbK0Kc97KlOULff3-iG2M7gURK-vxE5DYEGg&usqp=CAU',
        amount: 1,
        discount: 30,
        categories: [2, 3],
    },
];

export { products };
